# Generated by Django 5.2.1 on 2026-08-06 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_add_kyc_document_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="telegram_chat_id",
            field=models.BigIntegerField(
                blank=True,
                db_index=True,
                help_text="Telegram chat_id once the user has linked their account via the bot",
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_link_token",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="One-time token issued to the dashboard 'Connect Telegram' button; consumed on /start",
                max_length=64,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_link_token_created_at",
            field=models.DateTimeField(
                blank=True, help_text="Used to expire stale unclaimed tokens", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_linked_at",
            field=models.DateTimeField(
                blank=True, help_text="When the Telegram account was linked", null=True
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_notifications_enabled",
            field=models.BooleanField(
                default=True,
                help_text="Master toggle for Telegram push notifications (payouts, KYC, etc.)",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="telegram_username",
            field=models.CharField(
                blank=True,
                help_text="Telegram @username at time of linking",
                max_length=64,
                null=True,
            ),
        ),
    ]
